## @section nodeClasses
## Deploy Karpenter NodeClasses within this helm release
##
nodeClasses: {}
  # default:
  #   amiFamily: AL2
  #   subnetSelectorTerms:
  #     - tags:
  #         karpenter.sh/discovery: "${CLUSTER_NAME}"
  #         environment: test
  #     - id: subnet-09fa4a0a8f233a921
  #   securityGroupSelectorTerms:
  #     - tags:
  #         karpenter.sh/discovery: "${CLUSTER_NAME}"
  #         environment: test
  #     - name: my-security-group
  #     - id: sg-063d7acfb4b06c82c
  #   role: "KarpenterNodeRole-${CLUSTER_NAME}"
  #   instanceProfile: "KarpenterNodeInstanceProfile-${CLUSTER_NAME}"
  #   amiSelectorTerms:
  #     - tags:
  #         karpenter.sh/discovery: "${CLUSTER_NAME}"
  #         environment: test
  #     - name: my-ami
  #     - id: ami-123
  #   tags:
  #     team: team-a
  #     app: team-a-app
  #   metadataOptions:
  #     httpEndpoint: enabled
  #     httpProtocolIPv6: disabled
  #     httpPutResponseHopLimit: 1
  #     httpTokens: required
  #   detailedMonitoring: true
  #   associatePublicIPAddress: true

## @section nodePools
## Deploy Karpenter NodePools within this helm release
##
nodePools: {}
  # default:
  #   template:
  #     metadata:
  #       labels:
  #         billing-team: my-team
  #       annotations:
  #         example.com/owner: "my-team"
  #     spec:
  #       nodeClassRef:
  #         group: karpenter.k8s.aws
  #         kind: EC2NodeClass
  #         name: default
  #       taints:
  #         - key: example.com/special-taint
  #           effect: NoSchedule
  #       startupTaints:
  #         - key: example.com/another-taint
  #           effect: NoSchedule
  #       expireAfter: 720h
  #       terminationGracePeriod: 48h
  #       requirements:
  #         - key: "karpenter.k8s.aws/instance-category"
  #           operator: In
  #           values: ["c", "m", "r"]
  #           minValues: 2
  #         - key: "karpenter.k8s.aws/instance-family"
  #           operator: In
  #           values: ["m5","m5d","c5","c5d","c4","r4"]
  #           minValues: 5
  #         - key: "karpenter.k8s.aws/instance-cpu"
  #           operator: In
  #           values: ["4", "8", "16", "32"]
  #         - key: "karpenter.k8s.aws/instance-hypervisor"
  #           operator: In
  #           values: ["nitro"]
  #         - key: "karpenter.k8s.aws/instance-generation"
  #           operator: Gt
  #           values: ["2"]
  #         - key: "topology.kubernetes.io/zone"
  #           operator: In
  #           values: ["us-west-2a", "us-west-2b"]
  #         - key: "kubernetes.io/arch"
  #           operator: In
  #           values: ["arm64", "amd64"]
  #         - key: "karpenter.sh/capacity-type"
  #           operator: In
  #           values: ["spot", "on-demand"]
  #   disruption:
  #     consolidationPolicy: WhenEmptyOrUnderutilized
  #     consolidateAfter: 1m
  #     budgets:
  #     - nodes: 10%
  #     - schedule: "0 9 * * mon-fri"
  #       duration: 8h
  #       nodes: "0"
  #   limits:
  #     cpu: "1000"
  #     memory: 1000Gi
  #   weight: 10